### ISSUE TITLE
Google Map doesn't show up in example

### ISSUE THREAD

**Issue by luskah** [flask-extensions/Flask-GoogleMaps#142]
Hello, thanks for the work !

However, I can't even display the Google Maps in the example code.
I already have a key for these Google Maps API so I added **GoogleMaps(app, key = _mykey_)**
![image](https://user-images.githubusercontent.com/45620179/103418444-f30bad00-4b8e-11eb-861a-07faf02075a2.png)

Here is a screen of what I get one I run the python file:

![unnamed](https://user-images.githubusercontent.com/45620179/103418396-bd66c400-4b8e-11eb-9233-593f64c2c624.png)

Thank you if you can help  me figuring out where is the problem

**Comment by Herugrim** [comment]
I upgraded to 0.4.1 and encountered the same issue on my site. An omitted comma causes the javascript to break, I already made PR #143 to fix it.

**Comment by bhuveshsharma09** [comment]
Thank you @luskah for reporting the bug.
Thanks, @Herugrim for resolving it already.

**Comment by rohitabraham5** [comment]
Hello All, Any idea when will the changes be merged and pushed? Thanks in advance

**Comment by anafdal** [comment]
I am still having the same issue. Is there anything we can do?

**Comment by pcsagan** [comment]
The author is dead from COVID. It must be fixed manually.

**Comment by bhuveshsharma09** [comment]
Hey Guys,
Waiting for #144 to merge. That will resolve the issue.

Meanwhile, you can consider following the instruction given in #144 .

**Comment by Herugrim** [comment]
To be complete, PR #143 that fixes this bug was merged last week but no new release was done. In the meantime I made another PR #144 to iron out some extra things like loading unnecessary JavaScript. @bhuveshsharma09 could you please check out that PR? I asked for your input, if you can confirm that nothing breaks in the added functionality introduced in 0.4.1 then @Riverfount can merge #144 and create a new pip release. 

In the meantime you can either add a comma manually as per #143 or install 0.4.0 manually:
`pip install -I flask-googlemaps==0.4.0`

**Comment by Riverfount** [comment]
Hi guys I merged all the last PRs and create a new release of the extension. I hope that solves this issue.
